import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — NaukriYatra",
  description: "Terms of service for NaukriYatra. Educational platform disclaimer, user conduct rules, and service limitations.",
  keywords: "terms of service, terms and conditions, user agreement, NaukriYatra",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  const sections = [
    { title: "Acceptance of Terms", content: "By accessing and using NaukriYatra, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service." },
    { title: "Educational Platform Disclaimer", content: "NaukriYatra is an educational platform providing information and practice tools for government job preparation. All content is for informational purposes only. Users should verify information from official government sources before making decisions. We are not affiliated with UPSC, SSC, SBI, RRB, or any government body." },
    { title: "AI Interview Practice", content: "Our AI-powered mock interview tool is designed for practice purposes only. The questions and responses generated by AI may not reflect actual exam questions or evaluation criteria. Performance in practice sessions does not guarantee success in real examinations." },
    { title: "User Conduct", content: "Users must not use the platform for any illegal activities, harassment, or distribution of harmful content. Respect other users and maintain academic integrity. Sharing of login credentials or attempting to manipulate scores is prohibited." },
    { title: "Payment Terms", content: "Premium features are processed through Razorpay. All payments are final and non-refundable except as required by law. Subscription fees are billed in advance and automatically renew unless cancelled. Refunds are provided only in cases of technical issues preventing service access." },
    { title: "Intellectual Property", content: "All content, features, and functionality on NaukriYatra are owned by us or our licensors and are protected by copyright, trademark, and other intellectual property laws. Users may not reproduce, distribute, or create derivative works without permission." },
    { title: "Limitation of Liability", content: "NaukriYatra is provided 'as is' without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount paid by you for the service." },
    { title: "Account Termination", content: "We reserve the right to suspend or terminate accounts that violate these terms. Users may also terminate their accounts at any time through the dashboard settings." },
    { title: "Changes to Terms", content: "We may modify these terms at any time. Changes will be effective immediately upon posting. Continued use of the service after changes constitutes acceptance of the new terms." },
    { title: "Governing Law", content: "These terms are governed by the laws of India. Any disputes shall be resolved in the courts of New Delhi." },
    { title: "Contact Information", content: "For questions about these terms, please contact us at contact@naukriyatra.com." },
  ];

  return (
    <main style={{ minHeight: "100vh", background: "var(--bg)", paddingBottom: 80, paddingTop: 0 }}>
      <div className="desktop-only" style={{ height: 56 }} />
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "28px 20px" }}>
        <Link href="/" style={{ color: "#6B7280", fontSize: 13, textDecoration: "none" }}>← Back to Home</Link>
        <h1 style={{ fontFamily: "'Playfair Display',serif", fontSize: 28, fontWeight: 700, color: "#111827", marginTop: 16, marginBottom: 4 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: "#9CA3AF", marginBottom: 28 }}>Last updated: April 19, 2026</p>

        <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.7, marginBottom: 24 }}>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of NaukriYatra, an educational platform for government job preparation. By using our service, you agree to these terms.
        </p>

        {sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 20 }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 6 }}>{i + 1}. {s.title}</h2>
            <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.7 }}>{s.content}</p>
          </div>
        ))}
      </div>
    </main>
  );
}